### ISSUE TITLE
fix internal.rs

### ISSUE THREAD

**Issue by TopTen1004** [TopTen1004/rust-nft-digo#1]
I have some errors on internal.rs file

**Comment by towardsnewtech** [comment]
You should have change 2 second parameter like below

pub(crate) fn assert_one_yocto() {
    assert_eq!(
        env::attached_deposit(),
        2,
        "Requires attached deposit of exactly 1 yoctoNEAR"
    )
}

**Comment by towardsnewtech** [comment]
I am very pleased to fix this issue.
