### ISSUE TITLE
I have some errors in internal_remove_sale, Please, help me.

### ISSUE THREAD

**Issue by TopTen1004** [TopTen1004/rust-nft-digo#2]
pub(crate) fn internal_remove_sale(&mut self, nft_contract_id: AccountId, token_id: TokenId) -> Sale {
        let contract_and_token_id = format!("{}:{}", nft_contract_id, token_id);
        let sale = self.sales.remove(&contract_and_token_id).expect("No sale");

        let mut by_owner_id = self.by_owner_id.get(&sale.owner_id).expect("No sale");
        by_owner_id.remove(&contract_and_token_id);
        self.by_owner_id.insert(&sale.owner_id, &by_owner_id);

        let mut by_nft_contract_id = self.by_nft_contract_id.get(&nft_contract_id).expect("No sale");
        by_nft_contract_id.remove(&token_id);
        self.by_nft_contract_id.insert(&nft_contract_id, &by_nft_contract_id);

        sale
    }

**Comment by towardsnewtech** [comment]
let contract_and_token_id = format!("{}:{}", &nft_contract_id, token_id);

You should change like this.

**Comment by towardsnewtech** [comment]
I am very pleased to fix this issue.
